spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/momo_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        query:
          in_clause_parameter_padding: true # Hibernate에서 IN 절의 매개변수를 2의 거듭제곱 단위로 패딩하여 쿼리 캐시 효율성을 높이는 기능
        default_batch_fetch_size: 100
    open-in-view: false


application:
  security:
    jwt:
      secret-key: 462D4A614E645266556A586E3272357538782F413F4428472B4B625065536856
      expiration: 3600000 # 3600000 == 60분 // # 1800000 == 30분 // # 86400000 == 1일
      refresh-token:
        expiration: 2592000000 # 2592000000 == 30일 // # 604800000 == 7일

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.momo.backend: DEBUG
